name: CI

on:
  push:
    branches:
      - feat/**

jobs:
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      next-app: ${{ steps.next-app-changes.outputs.any_changed }}
      next-app-2: ${{ steps.next-app-2-changes.outputs.any_changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Next App changes
        id: next-app-changes
        uses: tj-actions/changed-files@v46
        with:
          files: apps/next-app/**

      - name: Check Next App 2 changes
        id: next-app-2-changes
        uses: tj-actions/changed-files@v46
        with:
          files: apps/next-app-2/**

            # 添加這段除錯訊息
      - name: Debug changed files output
        run: |
          echo "Next App changes detected: ${{ steps.next-app-changes.outputs.any_changed }}"
          echo "Next App 2 changes detected: ${{ steps.next-app-2-changes.outputs.any_changed }}"
          echo "Next App changed files: ${{ steps.next-app-changes.outputs.all_changed_files }}"
          echo "Next App 2 changed files: ${{ steps.next-app-2-changes.outputs.all_changed_files }}"

  lint-next-app:
    name: Lint next-app
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.next-app == 'true' }}
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup pnpm 9.0.0
        uses: pnpm/action-setup@v4
        with:
          version: 9.0.0

      - name: Setup Node.js 20 environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: |
          cd apps/next-app
          pnpm lint

  lint-next-app-2:
    name: Lint next-app-2
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.next-app-2 == 'true' }}
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup pnpm 9.0.0
        uses: pnpm/action-setup@v4
        with:
          version: 9.0.0

      - name: Setup Node.js 20 environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: |
          cd apps/next-app-2
          pnpm lint

  build-next-app:
    name: Build next-app
    needs: [detect-changes, lint-next-app]
    if: ${{ needs.detect-changes.outputs.next-app == 'true' }}
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup pnpm 9.0.0
        uses: pnpm/action-setup@v4
        with:
          version: 9.0.0

      - name: Setup Node.js 20 environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: |
          cd apps/next-app
          pnpm build

  build-next-app-2:
    name: Build next-app-2
    needs: [detect-changes, lint-next-app-2]
    if: ${{ needs.detect-changes.outputs.next-app-2 == 'true' }}
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup pnpm 9.0.0
        uses: pnpm/action-setup@v4
        with:
          version: 9.0.0

      - name: Setup Node.js 20 environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: |
          cd apps/next-app-2
          pnpm build